S03 u17 crud panneau news
WildCodeSchool/orleans-php-2003-project-rogertoulouse pull request #108
Opened 2020-05-05 08:19 UTC by benoitchocot

2020-05-05 09:17 UTC, Tisserandmat submitted a review, later dismissed

2020-05-05 17:22 UTC, ghost submitted a review, later dismissed

2020-05-06 09:20 UTC, Philippe-Naveilhan submitted a review, later dismissed
check

2020-05-06 09:20 UTC, Philippe-Naveilhan commented on src/View/HomeAdmin/_form.html.twig
> +               name="button_link" id="button_link"><br>
Pas de BR :) Il faut utiliser des div, les br sont réservées à la mise en page d'un texte... dixit Sylvain

2020-05-06 10:00 UTC, sblondeau requested changes
je ne relis pas :o  
je vous l'ai répété plusieurs fois, un CRUD ça correspond à au moins 4 US 
(index, add, edit, delete)
donc je veux au moins 4 PR différentes, pas tout dans une seule avec 15 fichiers
donc tu redécoupes ;-)

2020-05-06 11:05 UTC, Tisserandmat approved these changes

2020-05-06 14:08 UTC, sblondeau approved these changes

2020-05-06 14:16 UTC, merged