S04US17 ADD CRUD NEWS
WildCodeSchool/orleans-php-2003-project-rogertoulouse pull request #115
Opened 2020-05-06 15:28 UTC by benoitchocot

2020-05-06 15:39 UTC, ghost submitted a review, later dismissed

2020-05-06 18:49 UTC, ghost submitted a review, later dismissed

2020-05-07 08:30 UTC, sblondeau commented on src/Controller/HomeAdminController.php
> +        } elseif (strlen($data['title']) > 255) {
il faut aussi utiliser le $lengthControl dans ton if sinon ça sert à rien ;-)

2020-05-07 08:30 UTC, sblondeau commented on src/View/HomeAdmin/index.html.twig
> +                            <a href="/HomeAdmin/delete/{{ new.id }}">SUPPRIMER</a>
la suppression se gérera via un formualaire et pas un lien, sinon faille de sécurité :-)

2020-05-07 08:30 UTC, sblondeau requested changes

2020-05-07 08:30 UTC, sblondeau commented on src/Controller/HomeAdminController.php
> +        } elseif (strlen($data['desc']) > 255) {
idem

2020-05-07 10:30 UTC, Tisserandmat submitted a review, later dismissed

2020-05-07 11:22 UTC, sblondeau approved these changes

2020-05-07 11:22 UTC, merged