S004 us35 assoc info map contact
WildCodeSchool/orleans-php-2003-project-rogertoulouse pull request #119
Opened 2020-05-07 07:55 UTC by Tisserandmat

2020-05-07 11:24 UTC, sblondeau requested changes

2020-05-07 11:24 UTC, sblondeau commented on src/Controller/AssociationController.php
> +        $association = $assoc->selectOneById(1);
non pas d'id "en dur"
si tu n'as qu'une seule info à aller chercher dans ta table, tu dois plutot faire qqchose comme ça 
 "SELECT * FROM matable LIMIT 0, 1"

2020-05-08 11:59 UTC, ghost requested changes

2020-05-08 11:59 UTC, Tobe-Continued commented on src/Model/AssociationManager.php
> +        $statement->execute();
Cette fonction existe dans le AbstracManager, rajoute un argument optionel pour géré la limite ça évitera les fonction en double :S

2020-05-08 12:00 UTC, Tobe-Continued commented on src/Model/AssociationManager.php
> +        $statement->execute();
de plus, elle porte le même nom que l'autre fonction qui est appelé par AbstractManager du coup va y avoir des conflicts :S

2020-05-11 07:29 UTC, ghost requested changes

2020-05-11 07:29 UTC, Tobe-Continued commented on src/Model/AssociationManager.php
> +        $statement->execute();
Ya pas eu de changement ?

2020-05-11 15:25 UTC, ghost submitted a review, later dismissed

2020-05-11 16:12 UTC, sblondeau requested changes

2020-05-11 16:12 UTC, sblondeau commented on src/Controller/AssociationController.php
> +        $assoc = new AssociationManager();
$associationManager (pas d'abbreviation)

2020-05-11 16:12 UTC, sblondeau commented on src/Controller/AssociationController.php
> +        $association = $assoc->selectAll();
non, pas de selectAll ici car tu n'as qu'une ligne en bdd non ? 
il faut que tu créé une méthode selectFirst() dans ton manager
que cette méthode fasse un select * from self::TABLE LIMIT 0,1 
puis un fetch() et pas un fetchAll()

ainsi tu obtiens uniquement le 1er élément de ta table

2020-05-11 16:12 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                    <p>{{ association.0.text|nl2br }}</p>
et donc ici ce que tu récpères dans association est un tableau avec une dimension en moins, et tu n'as donc pas besoin de faire ce association.0.text, mais seulement association.text

2020-05-11 16:12 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                    <img src="/assets/upload/{{ association.0.image }}" class="card-img-top"
idem

2020-05-11 16:12 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                    <img src="/assets/upload/{{ association.0.image }}" class="card-img-top"
et plus bas aussi

2020-05-11 16:12 UTC, sblondeau commented on src/View/Association/index.html.twig
> +     <script src='https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.js'></script>
le js doit etre chargé en bas de page, dans un bloc javascript, juste AVANT la fermeture du body

2020-05-11 17:47 UTC, Tisserandmat commented on src/View/Association/index.html.twig
> +     <script src='https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.js'></script>
petit soucis mon script doit etre charger avant le script  ligne 71 si je le déplace juste avant la fermeture du body ma map ne s'affiche pas je vois pas comment faire autrement ..

2020-05-11 18:25 UTC, ghost approved these changes

2020-05-12 06:54 UTC, sblondeau approved these changes

2020-05-12 06:54 UTC, merged