S5 us36 delete
WildCodeSchool/orleans-php-2003-project-rogertoulouse pull request #143
Opened 2020-05-07 21:42 UTC by Philippe-Naveilhan

mise en place suppression avec étape de confirmation et requête préparée.

2020-05-08 12:01 UTC, ghost submitted a review, later dismissed

2020-05-09 06:35 UTC, sblondeau requested changes

2020-05-09 06:35 UTC, sblondeau commented on src/Model/ArtworkManager.php
> +        unlink('assets/upload/'.$picture);
le unlink je le mettrais plutot dans le controlleur apèrs l'apel de deleteArtwork. Ainsi, la suppression de l'image reste de la responsabilité du controleur et non du manager  et ça t'évite d'avoir à passer $picture en param

2020-05-09 06:35 UTC, sblondeau commented on src/View/ArtworksAdmin/index.html.twig
> +                        <form action="/ArtworksAdmin/delete/?act=delete" method="post">
je comprends pas bien la nécessité de passer ?act en paramètre, tu appelles déjà la route /delete pas besoin d'avoir une info supplémentaire via le GET

2020-05-09 06:35 UTC, sblondeau commented on src/View/ArtworksAdmin/index.html.twig
> +        {% if step == 'confirmDelete' %}
c'est trop compliqué ton truc avec les steps
tu devrais faire juste un form avec un champ id caché et un bouton delete par oeuvre à supprimer
si tu veux une confirmation, tu peux éventuellement faire un simple "confirm" en JS (c'est pas fou esthétiquement mais ça fait le job simplement) https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm

Ensuite quand on soumets ce form, on revient sur la meme page, tu captures le "POST", et tu execute le delete() du manager puis tu unlink un eventuel fichier si nécessaire, avant de faire une redirection via headerLocation.

rien besoin de faire coté vue mis à par le bouton du form

2020-05-09 06:35 UTC, sblondeau commented on src/Controller/ArtworksAdminController.php
> +        if (!empty($_GET['act']) && $_GET['act']=='delete' && (!empty($_POST['idArtwork']))) {
le delete se gère ne POST, je ne veux pas voir de GET par ici

2020-05-09 06:35 UTC, sblondeau commented on src/View/ArtworksAdmin/index.html.twig
> +        {% if step == 'confirmDelete' %}
eventuellement, tu peux passer dans le header Location un param message dans la query string pour gérer un message de "success" pour ta suppression

2020-05-09 19:38 UTC, ghost submitted a review, later dismissed

2020-05-11 06:59 UTC, sblondeau requested changes

2020-05-11 06:59 UTC, sblondeau commented on src/View/ArtworksAdmin/index.html.twig
> +                            <input type="text" name="pictureArtwork" value="{{ artwork.image }}" hidden>
juste un input name=idArtwork est suffisant
et c'est input type="hidden" et non type=text + attribut hidden

2020-05-11 06:59 UTC, sblondeau commented on src/Controller/ArtworksAdminController.php
> +            $picture = htmlentities($_POST['pictureArtwork']);
le hmtlentities est inutile
la picture doit etre recup via une requete en bdd selectOneById et non passé en POST ! sinon tu pourrais passer n'mporte quelle valeur et effacer le fichier correspondant, c'est dangereux ;-)

2020-05-11 07:27 UTC, ghost submitted a review, later dismissed

2020-05-11 07:46 UTC, sblondeau requested changes

2020-05-11 07:46 UTC, sblondeau commented on src/Controller/ArtworksAdminController.php
> +            return $this->twig->render('/ArtworksAdmin/index.html.twig', [
c'est un header location que je dois avoir ici et non un render
sinon tu vas avoir un soucis si tu reactualise la page
la méthode delete du controlleur n'a pas vocation a afficher une vue

2020-05-11 13:22 UTC, Tisserandmat approved these changes

2020-05-11 14:14 UTC, sblondeau approved these changes

2020-05-11 14:14 UTC, merged