S05 us40 update artwork
WildCodeSchool/orleans-php-2003-project-rogertoulouse pull request #147
Opened 2020-05-10 19:20 UTC by Philippe-Naveilhan

2020-05-10 20:51 UTC, ghost submitted a review, later dismissed

2020-05-11 07:40 UTC, sblondeau requested changes

2020-05-11 07:40 UTC, sblondeau commented on public/assets/css/adminArtworks.css
> +.updateArtworks .description{
CSS vides ?

2020-05-11 07:40 UTC, sblondeau commented on public/index.php
> +
attention à ne pas adder les fichiers inutiles pour cette US, je ne devais pas voir ce fichier ici ;-)

2020-05-11 07:40 UTC, sblondeau commented on src/Controller/ArtworksAdminController.php
> +            $artwork=$_POST;
et le trim ? :p

2020-05-11 07:40 UTC, sblondeau commented on src/Controller/ArtworksAdminController.php
> +            if (strlen($artwork['name'])>100) {
utilises des variable $nameLength pour gérer ta longueur max, et reutilises la dans le message d'erreur

2020-05-11 07:40 UTC, sblondeau commented on src/Controller/ArtworksAdminController.php
> +                $messages[]='Le champ TAILLE dne peut dépasser 40 caractères.';
revoir les messages d'erreur
- ici typo sur "dne"
- ne mets pas tes noms de champ en majuscule
- "info+" n'est pas très parlant

2020-05-11 13:57 UTC, Tisserandmat submitted a review, later dismissed

2020-05-11 13:57 UTC, ghost submitted a review, later dismissed

2020-05-11 14:44 UTC, sblondeau submitted a review, later dismissed

2020-05-11 14:44 UTC, sblondeau commented on src/Controller/ArtworksAdminController.php
> +        $sizeLenght=40;
Leng**th** pas lenght !

2020-05-11 16:02 UTC, Tisserandmat approved these changes

2020-05-11 16:13 UTC, merged