S01 us05
WildCodeSchool/orleans-php-2003-project-rogertoulouse pull request #16
Opened 2020-04-15 15:39 UTC by benoitchocot

2020-04-15 18:21 UTC, ghost submitted a review, later dismissed
Yes

2020-04-15 21:24 UTC, sblondeau requested changes

2020-04-15 21:24 UTC, sblondeau commented on public/assets/css/homepage.css
> +}
pas d'id pour gérer le style (donc pas de # dans ton fichier css, fait des classes)

2020-04-15 21:24 UTC, sblondeau commented on public/assets/css/homepage.css
> +
tu modifie h5, p, body
je penses que ce sont des styles propres à toutes les pages  du site non ?
leur place seraient donc plutot dans le fichier style.css general, plutot que dans celui ci ?

2020-04-15 21:24 UTC, sblondeau commented on src/View/Home/index.html.twig
> +                <img src="http://www.roger-toulouse.fr/peintre/45-48/photos/repasseu.jpg" class="d-block w-100"
le caroussel est-il administrable ? ça serait mieux :D 
dans tous les cas, meme si l'image est en dur, elle ne doit pas provenir d'un site externe, mais etre recopiée dans le projet
Le alt contient juste "...", tu dois y mettre une description textuelle de l'image

2020-04-15 21:24 UTC, sblondeau commented on src/View/Home/index.html.twig
> +                    <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
Là tu fais une US qui doit etre terminée.
Donc pas de Lorem ipsum, mais du texte final.
Si tu n'as pas le texte, demande au client de t'en fournir un.
Mais ici je pense que c'est le nom de l'oeuvre que tu voulais mettre non ?

2020-04-15 21:24 UTC, sblondeau commented on src/View/Home/index.html.twig
> +                    <h5>First slide</h5>
pas de h5 si tu n'as pas avant de h2, h3 et h4

2020-04-15 21:24 UTC, sblondeau commented on src/View/Home/index.html.twig
> +        </div>
le code pourrait etre optimisé avec une boucle car tu répètes beaucoup de choses

2020-04-15 21:24 UTC, sblondeau commented on src/routing.php
> +} elseif (empty($method)) {
meme remarque que pour la PR de philippe, et vous ne devriez pas avoir 2 fois la modifs dans 2 PR différentes...

2020-04-16 13:12 UTC, ghost submitted a review, later dismissed
Nickel

2020-04-16 15:23 UTC, sblondeau requested changes

2020-04-16 15:23 UTC, sblondeau commented on src/Controller/HomeController.php
> + * Class ItemController
HomeController, pense aussi à renommer dans les PHPDocs ;-)

2020-04-16 15:23 UTC, sblondeau commented on src/View/Home/index.html.twig
> +    <div id="carouselFade" class="carousel container col-7 mb-5 slide carousel-fade" data-ride="carousel">
tu me fais une requete vers une table pour récupérer des images dans le fichier précédent, et là tu fais le carousel "en dur". Il faut choirir l'un OU l'autre ;-)

2020-04-16 15:30 UTC, benoitchocot commented on src/Controller/HomeController.php
> + * Class ItemController
Petit oubli vu que c'était en commentaire, c'est fix

2020-04-16 15:39 UTC, benoitchocot commented on src/View/Home/index.html.twig
> +    <div id="carouselFade" class="carousel container col-7 mb-5 slide carousel-fade" data-ride="carousel">
Le hic c'est que je peux pas (ou ne sait pas) comment mettre cette partie dans la boucle à cause de la classe active du carousel (utilisée une fois mais essentielle pour le faire fonctionner). Comme je savais pas comment faire je l'ai laissée en dur en espérant que tu ne le remarques pas lol

2020-04-16 16:40 UTC, ghost approved these changes
ça me va

2020-04-16 19:38 UTC, sblondeau approved these changes

2020-04-16 19:38 UTC, sblondeau commented on src/Model/HomeManager.php
> +    const TABLE = 'carousel';
si ta table est carousel, tu devrais avoir un CarouselManager, plus logique
par contre tu peux garder un HomeController car tu appelles le carousel depuis la home

2020-04-16 19:39 UTC, merged