S01 us06
WildCodeSchool/orleans-php-2003-project-rogertoulouse pull request #21
Opened 2020-04-17 08:14 UTC by Tisserandmat

2020-04-17 10:06 UTC, ghost submitted a review, later dismissed
ok

2020-04-17 13:13 UTC, sblondeau requested changes

2020-04-17 13:13 UTC, sblondeau commented on public/assets/css/association.css
> +body{
si tu stylise body, c'est plutot dans style.css non ?

2020-04-17 13:13 UTC, sblondeau commented on public/assets/css/association.css
> +.part2_0{
hum, j'aime pas du tout tes noms de classes :D trouve moi un truc plus explicite que part2_0... et on utilise plutot les tirets que les underscores dans les noms de classe

2020-04-17 13:13 UTC, sblondeau commented on public/assets/css/association.css
> +.fa, .far, .fas {
idem ça c'est pour style.css

2020-04-17 13:13 UTC, sblondeau commented on public/assets/css/association.css
> +.jumbotron2{
nom de classe à revoir, pas de jumbotron2, card2 etc.
si c'est général, tu surchage jumbotron de bootstrap dans style.css
si c'est propre à ta page, tu créé une classe sur ton conteneur principal, association par ex, et tu stylise avec 
```css
.association. jumbotron {
...
}
```

2020-04-17 13:13 UTC, sblondeau commented on src/Controller/AssociationController.php
> +            var_dump($_POST);
un var_dump qui traine => gateau pour le code reviewer !

2020-04-17 13:13 UTC, sblondeau commented on src/Controller/AssociationController.php
> +            $data = $_POST;
non ! $data c'est $_POST sur lequel tu as fais un trim

2020-04-17 13:13 UTC, sblondeau commented on src/Model/AbstractManager.php
> +        return $this->pdo->query('SELECT * FROM  ' . $this->table)->fetchAll();
ce fichier ne devrait pas etre modifié, retire le de ta PR !

2020-04-17 13:13 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                            <h5 class="card-title">Contactez-nous</h5>
pas de h5 si tu n'as pas avant un h4, h3 etc

2020-04-17 13:13 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                        <div class="card-body">
il existe la balise html `<address>` pour mettre des coordonées, c'est mieux sémantiquement parlant

2020-04-17 13:13 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                            <label for="exampleFormControlInput1">Email</label>
revoit le nommage des tes "for" avec des noms explicites

2020-04-17 13:13 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                            <input type="text" name="object" class="form-control" placeholder="Ecrivez votre object"
revois tes placeholder, ça doit etre des exemples, pas des consignes (ça c'est le role du label)

2020-04-17 13:13 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
il te reste de l'anglais... 
attention aux copier/coller depuis le site de  bootstrap !

2020-04-17 13:13 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                <div class="card2 col-3" style="width: 18rem;">
pas de style en inline
attention aux copier/coller depuis le site de  bootstrap !

2020-04-17 13:13 UTC, sblondeau commented on src/View/Association/index.html.twig
> +            <script src='https://kit.fontawesome.com/4c4be71c0f.js' crossorigin="anonymous"></script>
je vois pas bien ce que ce fichier fais là ? c'est pas utilise pour charger fontawesome normalement :o 
et je crois que Philippe a mis le meme dans sa PR, mais dans le fichier layout direct... mettez vous d'accord ;-)

2020-04-17 13:13 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                        <a href="#" class="btn btn-primary">Voir l'oeuvre !</a>
œuvre et non oeuvre

2020-04-20 14:39 UTC, benoitchocot submitted a review, later dismissed

2020-04-21 06:59 UTC, sblondeau requested changes

2020-04-21 06:59 UTC, sblondeau commented on public/assets/css/association.css
> +form{
tu utilises 2 fois form, fusionne les 2
de plus, si ce sont de modifs génériques au form, c'est peut etre plus adapté dans style.css ?
pose toi la question à chaque fois si ta modif de style est que pour ta page ou pour tout le site, pour savoir dans quel fichier la placer. Y a peut-etre d'autres choses à bouger dans ton fichier du coup

2020-04-21 06:59 UTC, sblondeau commented on src/Controller/AssociationController.php
> +            $data = $_POST;
non modifié, reprends les livecoding si besoin. Ici tu ne fais pas de trim(), il faut que tu boucles sur $_POST et pour chaque élément, tu trim() la donnée et tu l'enregistre dans $data

2020-04-21 06:59 UTC, sblondeau commented on src/Controller/AssociationController.php
> +                var_dump($errors);
un var_dump qui traine=> Gateau ;-)

2020-04-21 06:59 UTC, sblondeau commented on src/Controller/AssociationController.php
> +            $data = array_map('trim', $_POST);
ah bah en fait tu fais ton trim là ! mais c'est AVANT de faire les validations qu'il faut trimer, donc remonte cette ligne ;-)

2020-04-21 06:59 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                        <h5 class="card-title">Contactez-nous</h5>
pas de h5 si pas de h4, h3... avant

2020-04-21 06:59 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                    <div class="card-body">
utilise la balise html `<address>` pour mettre des coordonnées. C'est mieux sémantiquement parlant

2020-04-21 06:59 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                        <label for="exampleFormControlSelect1">Object</label>
Object c'est en anglais. ici c'est objet ou sujet

2020-04-22 09:22 UTC, ghost submitted a review, later dismissed

2020-04-22 12:24 UTC, sblondeau requested changes

2020-04-22 12:24 UTC, sblondeau commented on public/assets/css/association.css
> +p i {
c'est général à tout le site ça.
et pas que dans les paragraphes d'ailleurs ?
donc plutot juste sur "i" et dans style.css

2020-04-22 12:24 UTC, sblondeau commented on public/assets/css/association.css
> +.formulaire{
nom de classes CSS en anglais stp

2020-04-22 12:24 UTC, sblondeau commented on public/assets/css/association.css
> + h2{
pb là ?

2020-04-22 12:24 UTC, sblondeau commented on src/Controller/AssociationController.php
> +            $email = ($data['email']);
pourquoi cette ligne ? c'est inutile, tu mets un elseif pour la ligne du filter_var et c'est bon sur $data['email']

2020-04-22 12:24 UTC, sblondeau commented on src/Controller/AssociationController.php
> +                $errors[] = 'message est requis';
retravaille tous tes messages d'erreur. Là il manque une "Le" devant message. Plus haut tu as mis "invalid" sans "e", etc. 
fait des belles phrases en français, sans faute, pense que ton user va les lire ces messages ;-)

2020-04-22 12:24 UTC, sblondeau commented on src/View/Association/index.html.twig
> +        <address class="col">Nous joindre </address>
non la balise address doit encadrer toutes les coordonnées.
Je la ferais donc commencer ligne 16 et finir ligne 24

2020-04-22 12:24 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                        <label for="exampleFormControlInput1">Email</label>
laisse pas des "exampleQuelqueChose" qui viennent de surement de la doc de bootstrap. Met des vrais id/for qui veulent dire qq chose par rapport à ton champ, ici "email" par ex

2020-04-22 12:24 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                    <p class="card-text">Description de l'oeuvre.</p>
œuvre pas oeuvre ;-)

2020-04-22 12:24 UTC, sblondeau commented on src/View/Association/index.html.twig
> +                <img class="card-img-top" src="http://terresdeloire.com/images/NOUVEAUSITE/2018/Toulouse/alerte.JPG"
non les images ne doivent pas provenir d'un autre site, mais etre stockées dans ton projet, car si le site en question ferme, le tiens s'en trouverait impacté avec une image qui ne s'afficherait plus.

2020-04-23 11:10 UTC, benoitchocot commented on src/Controller/AssociationController.php
>              $data = array_map('trim', $_POST);
manque tjrs un E à invalid

2020-04-23 11:32 UTC, Philippe-Naveilhan commented on src/View/Association/index.html.twig
> +     <link rel="stylesheet" href="/assets/css/association.css">{% endblock %}
Si tu reviens à al ligne après ton début de bloc, reviens aussi à la ligne pour ta fin de bloc, c'est plus lisible

2020-04-23 11:37 UTC, Philippe-Naveilhan requested changes
2 p'tites choses et c'est bon...

2020-04-23 11:39 UTC, Philippe-Naveilhan commented on src/Controller/AssociationController.php
>              $data = array_map('trim', $_POST);
C'est corrigé !

2020-04-23 11:40 UTC, Philippe-Naveilhan commented on src/Model/AbstractManager.php
> +        return $this->pdo->query('SELECT * FROM  ' . $this->table)->fetchAll();
c'est fait

2020-04-23 11:41 UTC, Philippe-Naveilhan submitted a review, later dismissed
C'est bon - corrections faites

2020-04-23 11:48 UTC, ghost requested changes

2020-04-23 11:48 UTC, Tobe-Continued commented on src/Model/AbstractManager.php
> +        return $this->pdo->query('SELECT * FROM  ' . $this->table)->fetchAll();
ya un espace en trop, après FROM ça peux créer des problèmes non ?

2020-04-23 14:04 UTC, Philippe-Naveilhan submitted a review, later dismissed
validation de associationManager (choix aléatoire d'une image)

2020-04-23 15:55 UTC, Philippe-Naveilhan submitted a review, later dismissed
C'est passé !

2020-04-23 18:34 UTC, sblondeau requested changes

2020-04-23 18:34 UTC, sblondeau commented on src/Controller/AssociationController.php
> +        $artworksManager = new ArtworkManager();
je ne comprends pas ce que les artworks font ici ?

2020-04-23 19:51 UTC, ghost approved these changes

2020-04-23 20:34 UTC, sblondeau approved these changes

2020-04-23 20:34 UTC, merged