Admin artwork confirm delete 197
WildCodeSchool/orleans-php-2003-project-rogertoulouse pull request #239
Opened 2020-05-13 22:27 UTC by Philippe-Naveilhan

Closes #197

2020-05-13 22:53 UTC, ghost submitted a review, later dismissed

2020-05-14 07:43 UTC, sblondeau requested changes

2020-05-14 07:43 UTC, sblondeau commented on src/View/ArtworksAdmin/index.html.twig
> +                        <form action="/ArtworksAdmin/preDelete/" method="post">
si je comprends bien, l'idée du preDelete est d'avoir une page qui permet de confirmer si on veut supprimer ou non ?
une fenetre "confirm" en JS est suffisant la plupart du temps, mais si vous voulez une page intermediaire, cette vue "delete.html.twig" contient le form pour valider la supprssion. Donc pour acceder à cette page, un simple lien suffit

2020-05-14 08:38 UTC, Philippe-Naveilhan commented on src/View/ArtworksAdmin/index.html.twig
> +                        <form action="/ArtworksAdmin/preDelete/" method="post">
C'est changé, mais du coup, l'ID passe en GET.

2020-05-14 08:55 UTC, ghost submitted a review, later dismissed

2020-05-14 09:06 UTC, sblondeau requested changes

2020-05-14 09:06 UTC, sblondeau commented on src/View/ArtworksAdmin/delete.html.twig
> +                <input name="idArtwork" value="{{ artwork.idArtwork }}" hidden>
utilise input type="hidden" plutot, il est fait pour ça !

2020-05-14 09:06 UTC, sblondeau commented on src/Controller/ArtworksAdminController.php
> +        if (isset($_GET['idArtwork'])) {
c'est bien compliqué pour pas grand chose :d 
pourquoi passe tu par le GET et la query string, alors que tu peux faire simplement /artworksAdmin/predelete/5
et recup cet id en param de ta fonction  ? :p

2020-05-14 09:15 UTC, Philippe-Naveilhan commented on src/Controller/ArtworksAdminController.php
> +        if (isset($_GET['idArtwork'])) {
aussi, c'est pas faux...

2020-05-14 09:31 UTC, Philippe-Naveilhan commented on src/View/ArtworksAdmin/delete.html.twig
> +                <input name="idArtwork" value="{{ artwork.idArtwork }}" hidden>
fait

2020-05-14 09:31 UTC, Philippe-Naveilhan commented on src/View/ArtworksAdmin/index.html.twig
> +                        <form action="/ArtworksAdmin/preDelete/" method="post">
C'est rechangé pas en GET

2020-05-14 09:37 UTC, benoitchocot approved these changes

2020-05-14 09:52 UTC, sblondeau approved these changes

2020-05-14 09:52 UTC, merged