Add HomeController disappear but why ? Probably my mistake, again...
WildCodeSchool/orleans-php-2003-project-rogertoulouse pull request #24
Opened 2020-04-17 13:34 UTC by Philippe-Naveilhan

Add HomeController.php disappeared...

2020-04-17 13:39 UTC, Philippe-Naveilhan commented
Add HomeController.php

2020-04-17 13:50 UTC, ghost submitted a review, later dismissed

2020-04-17 13:51 UTC, benoitchocot submitted a review, later dismissed

2020-04-17 14:06 UTC, benoitchocot submitted a review, later dismissed

2020-04-17 22:01 UTC, ghost submitted a review, later dismissed
Ça marche

2020-04-18 16:43 UTC, sblondeau requested changes

2020-04-18 16:43 UTC, sblondeau commented on src/Controller/HomeController.php
> +        $carouselManager = new HomeManager();
soucis de nommage là ? c'est new CarouselManger non ?

2020-04-18 16:49 UTC, Philippe-Naveilhan commented on src/Controller/HomeController.php
> +        $carouselManager = new HomeManager();
On travaille à 2 sur l'accueil. C'est la partie de Benoit récupérée sur DEV. Tu l'avais laissé passée celle-là ! ;) Je vois avec lui.

2020-04-20 07:54 UTC, benoitchocot approved these changes

2020-04-20 14:37 UTC, sblondeau approved these changes

2020-04-20 14:37 UTC, merged