Formulaire admin verif Empty Closes #203
WildCodeSchool/orleans-php-2003-project-rogertoulouse pull request #241
Opened 2020-05-13 22:39 UTC by Tisserandmat

2020-05-13 22:46 UTC, Philippe-Naveilhan submitted a review, later dismissed
check

2020-05-14 07:53 UTC, sblondeau requested changes

2020-05-14 07:53 UTC, sblondeau commented on src/Controller/AssociationAdminController.php
> +        foreach ($_POST as $key) {
hum... non je ne pense pas que ça convienne 
Là tu pars du principe que tous les champs sont obligatoire? c'est peut etre le cas mais il faut que tu vérifie $data (le $_POST sur lequel tu aras fais un trim) et pas direct $_POST. Car une espace seule sera pas empty et ta solution n'ira donc pas

2020-05-14 08:39 UTC, Philippe-Naveilhan approved these changes
check

2020-05-14 08:51 UTC, sblondeau approved these changes

2020-05-14 08:51 UTC, merged