S02 us11 accueil oeuvres list type
WildCodeSchool/orleans-php-2003-project-rogertoulouse pull request #28
Opened 2020-04-18 16:39 UTC by Philippe-Naveilhan

Chaque carte de la page d'accueil affiche une oeuvre d'une catégorie distincte.
Each card on homepage is a random artwork issue of one category.

2020-04-18 18:48 UTC, ghost requested changes

2020-04-18 18:48 UTC, Tobe-Continued commented on src/View/Home/index.html.twig
> +                <div class="carousel-item {% if loop.index == 1 %} active {% endif %}">
Tu devrais plutot utiliser un truc du genre {{ loop.index == 1 ? 'active'}}

2020-04-18 18:58 UTC, Philippe-Naveilhan commented on src/View/Home/index.html.twig
> +                <div class="carousel-item {% if loop.index == 1 %} active {% endif %}">
A voir avec Benoît, c’est lui qui gère le carrousel...

2020-04-19 01:19 UTC, ghost submitted a review, later dismissed

2020-04-20 15:03 UTC, sblondeau reviewed
j'ai le meme code que dans la PR précédente ? je lis pas le reste de la PR, pour moi y a un soucis au niveau de git là ;-) on en discute sur le slack si besoin

2020-04-20 19:13 UTC, closed without merging