S03 us03 oeuvres detail
WildCodeSchool/orleans-php-2003-project-rogertoulouse pull request #89
Opened 2020-04-27 22:42 UTC by Philippe-Naveilhan

page oeuvre seule

2020-04-28 11:10 UTC, ghost submitted a review, later dismissed

2020-04-28 11:51 UTC, sblondeau requested changes

2020-04-28 11:51 UTC, sblondeau commented on src/Controller/ArtworksController.php
> +    public function single($idArtwork)
les noms de méthode doivent pluto etre des verbes d'action
show() est utilisé généralement au lieu de single()
et pense à typer les param

2020-04-28 11:51 UTC, sblondeau commented on src/Model/ArtworkManager.php
> +    public function selectArtworks($categoryArtwork = null, $idArtwork = null):array
categoryArtwork et idArtwork sont des données venant de l'user, donc modifiable, donc il faut absolument que tu fasses une requete préparée sinon risque d'injection SQL
tu peux aussi typer tes param de fonction

2020-04-28 11:51 UTC, sblondeau commented on src/View/Artworks/see_artworks.html.twig
> +                            <img src="/assets/images/{{ artwork.category }}.svg"><br>{{ artwork.description }}
pas de br, ça sert uniquement à faire des sauts de lignes dans des paragraphes de texte, pas à faire de la mise en page, utilise un div par ex

2020-04-28 11:51 UTC, sblondeau commented on src/View/Artworks/see_artworks.html.twig
>                              {{ artwork.size }} <br> {{ artwork.more_info|nl2br }}
idem

2020-04-28 11:51 UTC, sblondeau commented on src/View/Home/carousel.html.twig
> +                    <a href="/Artworks/single/{{ slide.id }}"><img src="/assets/upload/{{ slide.image }}" class="d-block w-100 img-home"
à modif en show plutot que single

2020-05-05 10:14 UTC, ghost submitted a review, later dismissed

2020-05-05 10:54 UTC, ghost submitted a review, later dismissed

2020-05-05 13:45 UTC, benoitchocot submitted a review, later dismissed

2020-05-05 13:47 UTC, sblondeau requested changes

2020-05-05 13:47 UTC, sblondeau commented on src/Controller/ArtworksController.php
> +        $category = $_GET['cat'] ?? 'null';
c'est ?? '' ou ?? null
null est un type, si tu mets 'null' c'est la chaine de caractère 'null'

2020-05-05 13:47 UTC, sblondeau commented on src/Controller/ArtworksController.php
> +        $listIdCategories=[1,2,3,4];
tu ne list jamais d'id de BDD "en dur" 
si tu delete et rerempli ta base, les id auront changés

2020-05-05 13:47 UTC, sblondeau commented on src/Controller/ArtworksController.php
> +            $category ='';
tes if ne sont pas bon, déjà tu peux faire (int)$category si tu veux "forcé" le changement de type de string vers int
 ensuite si tu as une erreur, il faut que tu créé un tableau d'error, comme tu le fais pour la gestion en POST
et non pas mettre une chaine vide dans $category ;-)

2020-05-05 13:47 UTC, sblondeau commented on src/Controller/ArtworksController.php
> +        $listIdCategories=[1,2,3,4];
pour recup cette liste d'id, il faut que tu fasses une requete en BDD qui va recup toutes les categ, comme j'avais fais dans mon précédent livecoding avec les regions de vins

2020-05-05 13:47 UTC, sblondeau commented on src/Controller/ArtworksController.php
> +    public function single($idArtwork):string
ton $idArtwork doit etre typer un ing

2020-05-05 13:47 UTC, sblondeau commented on src/Controller/ArtworksController.php
> +        $idArtwork=intval($idArtwork);
donc cette ligne est inutile

2020-05-05 13:47 UTC, sblondeau commented on src/Controller/ArtworksController.php
> +        $seeArtworks = $artworkManager->selectArtworks(null, $idArtwork);
$artworks et pas $seeArtworks que tu traines encore depuis le début :D

2020-05-05 13:47 UTC, sblondeau commented on src/Controller/ArtworksController.php
> +        if (count($seeArtworks)!==1) {
ah... en fait non, si tu fais une requete en fonction d'un id, tu dois forcément avoir un seul résultat
donc en fait là ligne au dessus, c'est $artwork (au singulier) que tu récupère
qui sera le resultat d'un fetch() et pas d'un fetchAll()
if faudrait créer une méthode selectOneArtwork(int $id) dans ton manager

2020-05-05 13:47 UTC, sblondeau commented on src/View/Artworks/select.html.twig
> +                <img src="/assets/images/illustration.svg"><img src="/assets/images/peinture.svg"><img src="/assets/images/sculpture.svg"><img src="/assets/images/ecriture.svg"><br>
pas de br en dehors d'un paragraphe. fais un div plutot

2020-05-05 13:47 UTC, sblondeau commented on src/View/Artworks/single.html.twig
> +                <img src="/assets/images/{{ artwork.category }}.svg">{{ artwork.category|title }}<br>
idem partout ou tu as mis des br pour gérer un espacement vertical, ce n'est pas son but, le br sert à spécifier un changement de ligne dans un paragraphe de texte

2020-05-05 17:22 UTC, ghost submitted a review, later dismissed

2020-05-06 07:16 UTC, sblondeau requested changes
dans l'ensemble tu touches à beaucoup (trop) de fichiers sur cette PR, attention à ne modifier que les fichiers qui touchent uniquement à ta US

2020-05-06 07:16 UTC, sblondeau commented on src/Model/ArtworkManager.php
> +        $statement =$this->pdo->prepare($query);
attention, ce n'estp as une requete préparée ça, tu ne fait pas de bindValue ! c'est le bindValue avec le placeholder qui te permet de bénéficier des protections de la requete préparée. Si tu l'écris comme ça, c'est comme si tu faisais un simple $pdo->query()

2020-05-06 07:16 UTC, sblondeau commented on src/Model/ArtworkManager.php
> +        $statement =$this->pdo->prepare($query);
idem que ma remarque juste en dessous

2020-05-06 07:31 UTC, ghost approved these changes

2020-05-06 07:37 UTC, sblondeau approved these changes

2020-05-06 07:37 UTC, merged